import z from "zod";

import {
  BASE_EVENT_SCHEMA,
  USER_PNL_CREATED_PAYLOAD_SCHEMA,
  DEPTH_UPDATED_PAYLOAD_SCHEMA,
  ORDER_CANCELLED_PAYLOAD_SCHEMA,
  LIQUIDATION_COMPLETED_PAYLOAD_SCHEMA,
  LIQUIDATION_STARTED_PAYLOAD_SCHEMA,
  INDEXPRICE_UPDATED_PAYLOAD_SCHEMA,
  FUNDING_PAYLOAD_SCHEMA,
  ORDER_CREATED_PAYLOAD_SCHEMA,
  FILLS_CREATED_PAYLOAD_SCHEMA,
  TRADES_CREATED_PAYLOAD_SCHEMA,
  LAST_TRADED_PRICE_UPDATED_PAYLOAD_SCHEMA,
} from "./engineEventPayload.js";

// =======================================================================================

const USER_PNL_CREATED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: USER_PNL_CREATED_PAYLOAD_SCHEMA,
});

const DEPTH_UPDATED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: DEPTH_UPDATED_PAYLOAD_SCHEMA,
});

const ORDER_CANCELLED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: ORDER_CANCELLED_PAYLOAD_SCHEMA,
});

const LIQUIDATION_STARTED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: LIQUIDATION_STARTED_PAYLOAD_SCHEMA,
});

const LIQUIDATION_COMPLETED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: LIQUIDATION_COMPLETED_PAYLOAD_SCHEMA,
});

const INDEXPRICE_UPDATED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: INDEXPRICE_UPDATED_PAYLOAD_SCHEMA,
});

const FUNDING_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: FUNDING_PAYLOAD_SCHEMA,
});

const ORDER_CREATED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: ORDER_CREATED_PAYLOAD_SCHEMA,
});

const FILLS_CREATED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: FILLS_CREATED_PAYLOAD_SCHEMA,
});

const TRADES_CREATED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: TRADES_CREATED_PAYLOAD_SCHEMA,
});
const LAST_TRADED_PRICE_UPDATED_SCHEMA = BASE_EVENT_SCHEMA.extend({
  payload: LAST_TRADED_PRICE_UPDATED_PAYLOAD_SCHEMA,
});

// =======================================================================================

type USER_PNL_CREATED_EVENT = z.infer<typeof USER_PNL_CREATED_SCHEMA>;

type LIQUIDATION_STARTED_EVENT = z.infer<typeof LIQUIDATION_STARTED_SCHEMA>;
type LIQUIDATION_COMPLETED_EVENT = z.infer<typeof LIQUIDATION_COMPLETED_SCHEMA>;

type INDEXPRICE_UPDATED_EVENT = z.infer<typeof INDEXPRICE_UPDATED_SCHEMA>;

type LAST_TRADED_PRICE_UPDATED_EVENT = z.infer<
  typeof LAST_TRADED_PRICE_UPDATED_SCHEMA
>;

type TRADES_CREATED_EVENT = z.infer<typeof TRADES_CREATED_SCHEMA>;

type FUNDING_EVENT = z.infer<typeof FUNDING_SCHEMA>;

type ORDER_CREATED_EVENT = z.infer<typeof ORDER_CREATED_SCHEMA>;

type FILLS_CREATED_EVENT = z.infer<typeof FILLS_CREATED_SCHEMA>;

type ORDER_CANCELLED_EVENT = z.infer<typeof ORDER_CANCELLED_SCHEMA>;

// =======================================================================================

const ENGINE_EVENT_SCHEMA = z.union([
  DEPTH_UPDATED_SCHEMA,
  LIQUIDATION_COMPLETED_SCHEMA,
  TRADES_CREATED_SCHEMA,
  LAST_TRADED_PRICE_UPDATED_SCHEMA,
  FUNDING_SCHEMA,
  ORDER_CANCELLED_SCHEMA,
  LIQUIDATION_STARTED_SCHEMA,
  INDEXPRICE_UPDATED_SCHEMA,
  ORDER_CREATED_SCHEMA,
  FILLS_CREATED_SCHEMA,
  USER_PNL_CREATED_SCHEMA,
]);

type ENGINE_EVENT = z.infer<typeof ENGINE_EVENT_SCHEMA>;

// =======================================================================================
export { ENGINE_EVENT_SCHEMA };
export type { ENGINE_EVENT };

export {
  USER_PNL_CREATED_SCHEMA,
  DEPTH_UPDATED_SCHEMA,
  ORDER_CANCELLED_SCHEMA,
  LIQUIDATION_STARTED_SCHEMA,
  LIQUIDATION_COMPLETED_SCHEMA,
  INDEXPRICE_UPDATED_SCHEMA,
  FUNDING_SCHEMA,
  ORDER_CREATED_SCHEMA,
  FILLS_CREATED_SCHEMA,
  TRADES_CREATED_SCHEMA,
  LAST_TRADED_PRICE_UPDATED_SCHEMA,
};

export type {
  USER_PNL_CREATED_EVENT,
  LIQUIDATION_STARTED_EVENT,
  LIQUIDATION_COMPLETED_EVENT,
  INDEXPRICE_UPDATED_EVENT,
  LAST_TRADED_PRICE_UPDATED_EVENT,
  TRADES_CREATED_EVENT,
  FUNDING_EVENT,
  ORDER_CREATED_EVENT,
  FILLS_CREATED_EVENT,
  ORDER_CANCELLED_EVENT,
};
